### ISSUE TITLE
Hello plugin AlonsoPvP is not working paperspigot 1.12.2

### ISSUE THREAD

**Issue by nsktemperrr1** [AlonsoAliaga/AlonsoPvP#1]
**Describe the bug**
its not working

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: 0.1-BETA
 - Server version: git-paper-1618 (mc 1.12.2)

https://pastebin.pl/view/raw/340888da

**Comment by AlonsoAliaga** [comment]
Issue should be fixed now in 0.2-BETA
Let me know if error persists. 😄

Thanks for reporting!

**Comment by Flaimer2** [comment]
@AlonsoAliaga click the close button
